insert into PARTENAIRE (ID_PARTENAIRE, NOM_PARTENAIRE, MAIL_ARTENAIRE, TEL_PARTENAIRE) values (1, 'ENSIAS FORMATIONS', 'ENSIAS@ENSIAS', 19);
insert into PARTENAIRE (ID_PARTENAIRE, NOM_PARTENAIRE, MAIL_ARTENAIRE, TEL_PARTENAIRE) values (2,  BOSCO FORMATIONS', 'BOSCO@BOSCO', 18);
insert into PARTENAIRE (ID_PARTENAIRE, NOM_PARTENAIRE, MAIL_ARTENAIRE, TEL_PARTENAIRE) values (3, 'ESTEM FORMATIONS', 'ESTEM@ESTEM', 17);
insert into PARTENAIRE (ID_PARTENAIRE, NOM_PARTENAIRE, MAIL_ARTENAIRE, TEL_PARTENAIRE) values (4, 'ROCHELLE FORMATIONS', 'ROCHELLE@ROCHELLE', 16);
insert into PARTENAIRE (ID_PARTENAIRE, NOM_PARTENAIRE, MAIL_ARTENAIRE, TEL_PARTENAIRE) values (5, 'OFFOUMOU FORMATIONS', 'OFFOUMOU@OFFOUMOU', 15);

insert into FORMATEUR 
(ID_FORMATEUR, NOM_FORMATEUR, PREN_FORMATEUR, LOGIN_FORMATEUR, GENRE_FORMATEUR, CIN_FORMATEUR, DN_FORMATEUR, TEL_FORMATEUR, MAIL_FORMATEUR, PRO_FORMATEUR, MDP_FORMATEUR) 
values (2, 'BOHOUSSOU', 'YAO YANN VIANNEY', 'yano', 'M', 'BE63591Z', to_date('1995-7-07','YYYY-MM-DD'), 17, 'yannvianney@yahoo.fr', 'INGENIEUR', '070795');

insert into CLIENT 
(ID_CLIENT, NOM_CLIENT, PRENOM_CLIENT, LOGIN_CLIENT, GENRE_CLIENT, CIN_CLIENT, DN_CLIENT, TEL_CLIENT, MAIL_CLIENT, PRO_CLIENT, MDP_CLIENT) 
values (8, 'BOHOUSSOU', 'YAO YANN VIANNEY', 'yano', 'M', 'BE63591Z', to_date('1995-7-07','YYYY-MM-DD'), 17, 'yannvianney@yahoo.fr', 'INGENIEUR', '070795');

insert into RESPONSABLE 
(ID_RESPONSABLE, NOM_RESPONSABLE, PRENOM_RESONSABLE, LOGIN_RESPONSABLE, MDP_REPONSABLE) 
values 
(3, '8BOHOUSSOU', 'Yao Yann Vianney', 'yann', '070795');

insert into FORMATION 
(ID_FORMATION, TH_FORMATION, DESC_FORMATION) 
values (1, 'INFORMATIQUE', 'JAVA');

insert into SSSESSION 
(ID_SESSION, ID_FORMATEUR, ID_FORMATION, DATE_DEB_SESSION, PRIX_SESSION, PLA_SESSION, DUREE_SESSION, PROG_SESSION) 
values (1, 2, 1, to_date('2015-7-07','YYYY-MM-DD'), 200, 18, 30, 'prog');

insert into SSSESSION 
(ID_SESSION, ID_FORMATEUR, ID_FORMATION, DATE_DEB_SESSION, PRIX_SESSION, PLA_SESSION, DUREE_SESSION, PROG_SESSION) 
values (2, 2, 1, to_date('2015-12-07','YYYY-MM-DD'), 700, 18, 30, 'prog');
